### PR TITLE
abicheck.sh: don't export CHOST if it wasn't already exported.

### LINKED ISSUE #1219: Regression: abicheck.sh fails with strange compilation error when building zlib-ng
Symptom:
```
$ sh test/abicheck.sh --refresh-if
...
/usr/bin/ld: zutil.lo: warning: relocation against `zng_z_errmsg' in read-only section `.text'
/usr/bin/ld: adler32.lo: relocation R_X86_64_PC32 against symbol `functable' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make: *** [Makefile:268: libz-ng.so.2.0.0] Error 1
```

This appears to be because exporting CHOST causes zlib-ng's configure script to set CROSS_PREFIX, and then the test
```
if test "$gcc" -eq 1 && ($cc $CFLAGS -c $test.c) >> configure.log 2>&1; then
```
fails because the host compiler isn't available with a cross name, leading to a whole big block of code getting skipped, including the code that adds -fPIC.

Looks like this is a regression introduced by https://github.com/zlib-ng/zlib-ng/commit/a1a807b814e9b1990dda4f80ebc73896c5410acd

### PR DESCRIPTION
**Pull request by dkegel-fastly**
This should fix https://github.com/zlib-ng/zlib-ng/issues/1219,
a regression when running abicheck.sh with default compiler, without breaking anything else.

Bit subtle, so deserves careful review.  See https://github.com/zlib-ng/zlib-ng/issues/705#issuecomment-766523874 for original reason for the change being reverted, which I now think was mistaken because it missed the note about why it was important to not export CHOST in the default compiler case.

(Untested locally at the moment because I'm traveling with the wrong laptop, and this is its first test on its own in CI, but tested previously at home and as part of https://github.com/zlib-ng/zlib-ng/pull/1220.)

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Looks pretty straightforward.

**Comment by dkegel-fastly** [comment]
See https://github.com/zlib-ng/zlib-ng/pull/1222 for the fix for the codefactor notice.

**Comment by dkegel-fastly** [comment]
Great... could you approve running the workflow?  Thanks...

**Comment by dkegel-fastly** [comment]
Thank you.  Looks ready to go.

**Review by Dead2 — APPROVED** [review]
