### ISSUE TITLE
Regression: abicheck.sh fails with strange compilation error when building zlib-ng

### ISSUE THREAD

**Issue by dankegel** [zlib-ng/zlib-ng#1219]
Symptom:
```
$ sh test/abicheck.sh --refresh-if
...
/usr/bin/ld: zutil.lo: warning: relocation against `zng_z_errmsg' in read-only section `.text'
/usr/bin/ld: adler32.lo: relocation R_X86_64_PC32 against symbol `functable' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make: *** [Makefile:268: libz-ng.so.2.0.0] Error 1
```

This appears to be because exporting CHOST causes zlib-ng's configure script to set CROSS_PREFIX, and then the test
```
if test "$gcc" -eq 1 && ($cc $CFLAGS -c $test.c) >> configure.log 2>&1; then
```
fails because the host compiler isn't available with a cross name, leading to a whole big block of code getting skipped, including the code that adds -fPIC.

Looks like this is a regression introduced by https://github.com/zlib-ng/zlib-ng/commit/a1a807b814e9b1990dda4f80ebc73896c5410acd

**Comment by nmoinvaz** [comment]
I think this might be convered in the wiki. Maybe use different linker..

**Comment by mtl1979** [comment]
This is a bug in zlib's configure; I've already reported it.

**Comment by dankegel** [comment]
Well.... maybe not quite.  I am describing a zlib-ng-only problem, not a zlib problem, so this is not related to https://github.com/madler/zlib/issues/617, though the symptom and causes are very similar to that.

See the fix I propose in #1220.

It seems that running zlib-ng's configure with CHOST set is a user error if the self-cross is not installed, so abicheck.sh shouldn't do it.

**Comment by mtl1979** [comment]
In my Linux, both /usr/bin/cc and /usr/bin/gcc are symbolic links to non-canonicalized name, for example /usr/bin/x86_64-linux-gnu-gcc-11, so using CHOST works for both zlib-ng and zlib. However zlib 1.2.12 sets "uname" to "gnu" due to bug in PCRE used to parse CHOST, so CC needs to be explicitly set.

**Comment by dankegel** [comment]
I was using a freshly installed ubuntu 20.04 beta, with compiler installed via "apt install build-essential".

Which Linux are you using?

**Comment by mtl1979** [comment]
> I was using a freshly installed ubuntu 20.04 beta, with compiler installed via "apt install build-essential".
> 
> Which Linux are you using?
> 

18.04 up to 22.04 beta... Basically all releases still supported, only installed "gcc", "g++", "clang"  and of course cmake, make and git.

**Comment by dankegel** [comment]
Again, let me emphasize, this bug has nothing whatsoever to do with zlib.  It is solely a bug in zlib-ng/test/abicheck.sh and/or zlib-ng/configure.

Let's see what the compiler story is:
```
$ ls -l /usr/bin/gcc
lrwxrwxrwx 1 root root 6 Aug  5  2021 /usr/bin/gcc -> gcc-11
$ dpkg-query -S /usr/bin/gcc-11
gcc-11: /usr/bin/gcc-11
$ ls -l  /usr/bin/gcc-11
lrwxrwxrwx 1 root root 23 Mar 24 14:22 /usr/bin/gcc-11 -> x86_64-linux-gnu-gcc-11
$ cat /etc/issue
Ubuntu Jammy Jellyfish (development branch) \n \l
```

I think the problem may be that CHOST is canonicalized, er, differently?  Yup:
```
$ tools/config.sub x86_64-linux-gnu
x86_64-pc-linux-gnu
```

So it's a lead-pipe cinch that ${CROSS_PREFIX}-gcc won't be found, and abicheck.sh will fail.

One should not need to set CC for abicheck.sh to build zlib-ng properly when simply doing a run with plain old gcc.

Anyway, it's just not a good assumption that a self-cross compiler is available, and we shouldn't make it.

**Comment by dankegel** [comment]
Another way to fix it would be to revert https://github.com/zlib-ng/zlib-ng/commit/a1a807b814e9b1990dda4f80ebc73896c5410acd

What prompted that commit, anyway?

**Comment by mtl1979** [comment]
@dankegel I removed the canonicalization like I already mentioned, but building zlib 1.2.12 still failed, so it was clearly regression in zlib. Specifying explicitly both CHOST and CC works correctly with zlib 1.2.12.1 however and gives two changed symbols.

**Comment by dankegel** [comment]
Yes, that matches my results with https://github.com/zlib-ng/zlib-ng/pull/1220 applied.

**Comment by mtl1979** [comment]
https://github.com/madler/zlib/commit/73014202489f913dbffc91d22089ea8a8920c054#diff-90d08e583c4c9c6f391b2ae90f819f600a6326928ea9512c9e0c6d98e9f29ac2L17

That change in zlib way back broke the detecting of Debian/Ubuntu architectures, basically it changed picking third instead of second segment of the triplet.

That is why zlib 1.2.11 and earlier needed canonicalization.

**Comment by dankegel** [comment]
Thank you for being specific.  

How can I reproduce the problem a1a807b814 fixed?  This doesn't reproduce it here:

    $ git reset --hard a1a807b814^ 
    $ test/abicheck.sh --refresh --zlib-compat
    $ test/abicheck.sh --refresh

and this fails with the problem the change was trying to prevent, as well as causing it in zlib-ng:

    $ git reset --hard a1a807b814
    $ test/abicheck.sh --refresh --zlib-compat
    /usr/bin/ld: trees.lo: warning: relocation against `_length_code' in read-only section `.text'
    make: *** [Makefile:282: libz.so.1.2.11] Error 1
    $ test/abicheck.sh --refresh
     /usr/bin/ld: zutil.lo: warning: relocation against `zng_z_errmsg' in read-only section `.text'
     make: *** [Makefile:268: libz-ng.so.2.0.0-RC1] Error 1

**Comment by mtl1979** [comment]
Stock zlib requires `CC` to be always set, even when using `CHOST`... It also requires the file not to be symlink, so I used `$(readlink -f $(which cc))` to resolve all the symbolic links when not cross-compiling. With cross-compiling, you need to use non-canonicalized `CHOST` and append `-gcc`, appending plain `-cc` doesn't work reliably.

The important part is that value of `CC` contains `gcc` and not just `cc`.

**Comment by dankegel** [comment]
It looks like stock zlib compiled fine in the above example without CC or CHOST being set:

    $ git reset --hard a1a807b814^ 
    $ test/abicheck.sh --refresh --zlib-compat

Stock zlib might require CC to be set when setting CHOST to work around broken canonicalization.
But both zlib and zlib-ng work properly without CC or CHOST set if you just want to use the host compiler, I think.  Right?

**Comment by mtl1979** [comment]
There is small number of commits of stock zlib that don't automatically use gcc first and default to cc which cause linker errors when building shared library... There is a lot more of commits that default to gcc and as such can build shared library when not cross-compiling.

The issue with `CHOST` comes to the fact that zlib's configure requires `-pc-` in it but the gcc binary doesn't have it.

**Comment by dankegel** [comment]
Happily for abicheck.sh, the only commits of zlib we care about are those which are used as ABI references,
so 1.2.11 and 1.2.12.  And those, I think, work properly with CC and CHOST unset.

i.e. zlib's configure does not require -pc- in the binary when using the default compiler (for the commits abicheck.sh cares about).

Does that seem accurate?

**Comment by mtl1979** [comment]
> Happily for abicheck.sh, the only commits of zlib we care about are those which are used as ABI references, so 1.2.11 and 1.2.12. And those, I think, work properly with CC and CHOST unset.
> 
> i.e. zlib's configure does not require -pc- in the binary when using the default compiler (for the commits abicheck.sh cares about).
> 
> Does that seem accurate?

It doesn't require when _both_ are unset. zlib 1.2.12 only had issues when `CC` is set as its value was ignored.

**Comment by nmoinvaz** [comment]
@dankegel see my comment at https://github.com/zlib-ng/zlib-ng/issues/705#issuecomment-766523874 for why the `CHOST` stuff was changed. It looks like nobody ever responded to it.

**Comment by dankegel** [comment]
Sweet!  Thank you for digging that up!

**Comment by mtl1979** [comment]
@nmoinvaz I hardly ever respond to issues I'm not familiar with... It takes quite a while for me to dig up every detail about something specific and memorize it. I also have other projects I'm working on at the same time, so I don't follow every discussion 24/7.

**Comment by dkegel-fastly** [comment]
OK!  After reviewing https://github.com/zlib-ng/zlib-ng/issues/705#issuecomment-766523874, I think:
- https://github.com/zlib-ng/zlib-ng/commit/a1a807b814e9b1990dda4f80ebc73896c5410acd was speculative
- it was not needed to fix CI, so reverting it would not break CI
- it missed the important detail that abicheck.sh does not export the canonicalized CHOST if CHOST was not already exported

Canonicalization is still a good idea, so the .abi file can have a consistent name, but exporting in the no-chost case causes the observed problem.  So my proposed fix of simply dropping the word export is probably optimal.

I will draft a fresh PR accordingly.  Thank you for the careful review and the details.
