### ISSUE TITLE
build failure: "undefined reference to 'getauxval'" when trying to build with optimization for arm

### ISSUE THREAD

**Issue by ReOne21** [zlib-ng/zlib-ng#839]
When trying to build the project with optimizations for ARM i am getting this error:

```
C:/msys64/home/zlib-ng-develop/arch/arm/armfeature.c:39: error: undefined reference to 'getauxval'
C:/msys64/home/zlib-ng-develop/arch/arm/armfeature.c:19: error: undefined reference to 'getauxval'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/zlib.dir/build.make:522: libz.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:117: CMakeFiles/zlib.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```
it's only appears when using optimization

**Comment by nmoinvaz** [comment]
Please provide OS and compiler information and configure log.

**Comment by ReOne21** [comment]
I generated makefiles with cmake-gui and then tried to build with make. Same errors appears on such configurations:
MacOS 10.13 when trying to build with Xcode 7.0.3 for iOS
Windows 7 with MSYS2 and Android NDK, using Clang compiler when trying build for Android
and all these errors only when building for arm with optimization
Maybe I don't understand something?

**Comment by ReOne21** [comment]
Is that configure log?
```
Using CMake version 3.19.3
ZLIB_HEADER_VERSION: 1.2.11
ZLIBNG_HEADER_VERSION: 2.0.0-RC2
ANDROID_PLATFORM not set. Defaulting to minimum supported version
16.
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/msys64/home/android-ndk-r21e-windows-x86_64/android-ndk-r21e/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe - skipped
Detecting C compile features
Detecting C compile features - done
Arch detected: 'armv7-none-linux-androideabi16'
Basearch of 'armv7-none-linux-androideabi16' has been detected as: 'arm'
Using CMake toolchain: C:/msys64/home/android-ndk-r21e-windows-x86_64/android-ndk-r21e/build/cmake/android.toolchain.cmake
ARM floating point arch: 
Performing Test MFPU_NEON_AVAILABLE
Performing Test MFPU_NEON_AVAILABLE - Success
Architecture supports unaligned reads
Architecture supports unaligned reads of > 4 bytes
Looking for sys/types.h
Looking for sys/types.h - found
Looking for stdarg.h
Looking for stdarg.h - found
Looking for stdint.h
Looking for stdint.h - found
Looking for stddef.h
Looking for stddef.h - found
Looking for sys/sdt.h
Looking for sys/sdt.h - not found
Looking for unistd.h
Looking for unistd.h - found
Check size of off64_t
Check size of off64_t - done
Looking for fseeko
Looking for fseeko - found
Looking for strerror
Looking for strerror - found
Performing Test HAVE_NO_INTERPOSITION
Performing Test HAVE_NO_INTERPOSITION - Failed
Performing Test HAVE_ATTRIBUTE_VISIBILITY_HIDDEN
Performing Test HAVE_ATTRIBUTE_VISIBILITY_HIDDEN - Success
Performing Test HAVE_ATTRIBUTE_VISIBILITY_INTERNAL
Performing Test HAVE_ATTRIBUTE_VISIBILITY_INTERNAL - Success
Performing Test HAVE_BUILTIN_CTZ
Performing Test HAVE_BUILTIN_CTZ - Success
Performing Test HAVE_BUILTIN_CTZLL
Performing Test HAVE_BUILTIN_CTZLL - Success
Performing Test HAVE_PTRDIFF_T
Performing Test HAVE_PTRDIFF_T - Success
Architecture-specific source files: arch/arm/armfeature.c;arch/arm/crc32_acle.c;arch/arm/insert_string_acle.c;arch/arm/adler32_neon.c;arch/arm/chunkset_neon.c;arch/arm/slide_neon.c
The following features have been enabled:

 * CMAKE_BUILD_TYPE, Build type: Release (default)
 * WITH_GZFILEOP, Compile with support for gzFile related functions
 * ZLIB_ENABLE_TESTS, Build test binaries
 * WITH_OPTIM, Build with optimisation
 * WITH_NEW_STRATEGIES, Use new strategies
 * WITH_UNALIGNED, Support unaligned reads on platforms that support it
 * WITH_ACLE, Build with ACLE
 * WITH_NEON, Build with NEON intrinsics
 * ACLE_CRC, Support ACLE optimized CRC hash generation, using "-march=armv8-a+crc"
 * NEON_ADLER32, Support NEON instructions in adler32, using "-mfpu=neon"
 * NEON_SLIDEHASH, Support NEON instructions in slide_hash, using "-mfpu=neon"

-- The following features have been disabled:

 * ZLIB_COMPAT, Compile with zlib compatible API
 * ZLIB_DUAL_LINK, Dual link tests against system zlib
 * WITH_SANITIZER, Build with sanitizer (Memory, Address, Undefined)
 * WITH_FUZZERS, Build test/fuzz
 * WITH_NATIVE_INSTRUCTIONS, Instruct the compiler to use the full instruction set on this host (gcc/clang -march=native)
 * WITH_MAINTAINER_WARNINGS, Build with project maintainer warnings
 * WITH_CODE_COVERAGE, Enable code coverage reporting
 * WITH_INFLATE_STRICT, Build with strict inflate distance checking
 * WITH_INFLATE_ALLOW_INVALID_DIST, Build with zero fill for inflate invalid distances
 * INSTALL_UTILS, Copy minigzip and minideflate during install

Configuring done
```

**Comment by ReOne21** [comment]
Full make log:
```
$ make
Scanning dependencies of target zlib
[  1%] Building C object CMakeFiles/zlib.dir/adler32.c.o
[  2%] Building C object CMakeFiles/zlib.dir/chunkset.c.o
[  3%] Building C object CMakeFiles/zlib.dir/compare258.c.o
[  4%] Building C object CMakeFiles/zlib.dir/compress.c.o
[  6%] Building C object CMakeFiles/zlib.dir/crc32.c.o
[  7%] Building C object CMakeFiles/zlib.dir/crc32_comb.c.o
[  8%] Building C object CMakeFiles/zlib.dir/deflate.c.o
[  9%] Building C object CMakeFiles/zlib.dir/deflate_fast.c.o
[ 10%] Building C object CMakeFiles/zlib.dir/deflate_medium.c.o
[ 12%] Building C object CMakeFiles/zlib.dir/deflate_quick.c.o
[ 13%] Building C object CMakeFiles/zlib.dir/deflate_slow.c.o
[ 14%] Building C object CMakeFiles/zlib.dir/functable.c.o
[ 15%] Building C object CMakeFiles/zlib.dir/infback.c.o
[ 17%] Building C object CMakeFiles/zlib.dir/inffast.c.o
[ 18%] Building C object CMakeFiles/zlib.dir/inflate.c.o
[ 19%] Building C object CMakeFiles/zlib.dir/inftrees.c.o
[ 20%] Building C object CMakeFiles/zlib.dir/insert_string.c.o
[ 21%] Building C object CMakeFiles/zlib.dir/trees.c.o
[ 23%] Building C object CMakeFiles/zlib.dir/uncompr.c.o
[ 24%] Building C object CMakeFiles/zlib.dir/zutil.c.o
[ 25%] Building C object CMakeFiles/zlib.dir/arch/arm/armfeature.c.o
C:/msys64/home/zlib-ng-develop/arch/arm/armfeature.c:19:13: warning: implicit declaration of function 'getauxval' is invalid in C99 [-Wimplicit-function-declaration]
    return (getauxval(AT_HWCAP2) & HWCAP2_CRC32) != 0 ? 1 : 0;
            ^
C:/msys64/home/zlib-ng-develop/arch/arm/armfeature.c:39:13: warning: implicit declaration of function 'getauxval' is invalid in C99 [-Wimplicit-function-declaration]
    return (getauxval(AT_HWCAP) & HWCAP_NEON) != 0 ? 1 : 0;
            ^
2 warnings generated.
[ 26%] Building C object CMakeFiles/zlib.dir/arch/arm/crc32_acle.c.o
[ 28%] Building C object CMakeFiles/zlib.dir/arch/arm/insert_string_acle.c.o
[ 29%] Building C object CMakeFiles/zlib.dir/arch/arm/adler32_neon.c.o
[ 30%] Building C object CMakeFiles/zlib.dir/arch/arm/chunkset_neon.c.o
[ 31%] Building C object CMakeFiles/zlib.dir/arch/arm/slide_neon.c.o
[ 32%] Building C object CMakeFiles/zlib.dir/gzlib.c.o
[ 34%] Building C object CMakeFiles/zlib.dir/gzread.c.o
[ 35%] Building C object CMakeFiles/zlib.dir/gzwrite.c.o
[ 36%] Linking C shared library libz-ng.so
C:/msys64/home/zlib-ng-develop/arch/arm/armfeature.c:39: error: undefined reference to 'getauxval'
C:/msys64/home/zlib-ng-develop/arch/arm/armfeature.c:19: error: undefined reference to 'getauxval'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/zlib.dir/build.make:522: libz-ng.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:115: CMakeFiles/zlib.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```

**Comment by mtl1979** [comment]
The error is here:
```ANDROID_PLATFORM not set. Defaulting to minimum supported version 16.```

Minimum supported is 18.

**Comment by ReOne21** [comment]
Thanks, now it builds for Android without errors.

**Comment by ReOne21** [comment]
If there will be are any problems with macOS or iOS building, then I will create a new topic, as it should have been. Thanks again.
