### ISSUE TITLE
AppleClang 8: error: initializing '__m256i' (vector of 4 'long long' values) with an expression of incompatible type 'int'

### ISSUE THREAD

**Issue by seanm** [zlib-ng/zlib-ng#1264]
I library I use ([ITK](https://github.com/InsightSoftwareConsortium/ITK)) recently updated to [zlib-ng 2022-04-27 (d41f8ead)](https://github.com/InsightSoftwareConsortium/ITK/pull/3275#) (*from* what I'm not sure) and it now fails to build on macOS 10.11 with AppleClang 8, with:

```
/Users/builder/external/ITK/Modules/ThirdParty/ZLIB/src/itkzlib-ng/arch/x86/adler32_avx2.c:55:13: error: initializing '__m256i' (vector of 4 'long long' values) with an expression
      of incompatible type 'int'
    __m256i vs1 = _mm256_zextsi128_si256(_mm_cvtsi32_si128(adler));
            ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/builder/external/ITK/Modules/ThirdParty/ZLIB/src/itkzlib-ng/arch/x86/adler32_avx2.c:56:13: error: initializing '__m256i' (vector of 4 'long long' values) with an expression
      of incompatible type 'int'
    __m256i vs2 = _mm256_zextsi128_si256(_mm_cvtsi32_si128(sum2));
            ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

See: https://open.cdash.org/viewBuildError.php?buildid=7889929

Perhaps `X86_AVX2_ADLER32` should not be set for this compiler and/or macOS deployment target?

**Comment by mtl1979** [comment]
This seems to be missing the initial error, which is that those intrinsic functions have no prototype defined. You should try to find out if it is because the correct header is not included, or if the compiler doesn't support those intrinsics, or that those intrinsics have different names.

**Comment by seanm** [comment]
Yup, there's just no declaration of `_mm256_zextsi128_si256` in Xcode 8:

```
$ cat test.c
#include <x86intrin.h> 

__m256i zero_upper_part(__m256i a) {
   return _mm256_zextsi128_si256(_mm256_castsi256_si128(a));
}

$ xcrun clang -mavx2 -fsyntax-only test.c
test.c:4:11: warning: implicit declaration of function '_mm256_zextsi128_si256' is invalid in C99 [-Wimplicit-function-declaration]
   return _mm256_zextsi128_si256(_mm256_castsi256_si128(a));
          ^
test.c:4:11: error: returning 'int' from a function with incompatible result type '__m256i' (vector of 4 'long long' values)
   return _mm256_zextsi128_si256(_mm256_castsi256_si128(a));
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by mtl1979** [comment]
You should try modifying `fallback_builtins.h`, so it uses the fallback version... I don't have AppleClang, so I can't make a patch.
AppleClang should have `__apple_build_version__` defined.

**Comment by KungFuJesus** [comment]
That's odd, clang definitely had this on Linux when I was testing.  The fallback there with assembly will probably work fine for you as well.

**Comment by seanm** [comment]
I'm not sure it's a Clang vs AppleClang thing, it's maybe more a question of the system headers.  The older Xcode's don't have that symbol in any .h file.

**Comment by KungFuJesus** [comment]
That may very well be.  Though, compiler intrinsics like this at least are typically distributed with the compiler, not a libc implementation.  
See my grep result in /usr/lib on Linux:
```
/usr/lib/clang/12.0.1/include/avx512fintrin.h:_mm512_zextsi128_si512(__m128i __a)
/usr/lib/clang/12.0.1/include/avx512fintrin.h:_mm512_zextsi256_si512(__m256i __a)
/usr/lib/clang/12.0.1/include/avxintrin.h:_mm256_zextsi128_si256(__m128i __a)
/usr/lib/clang/13.0.1/include/avxintrin.h:_mm256_zextsi128_si256(__m128i __a)
/usr/lib/clang/13.0.1/include/avx512fintrin.h:_mm512_zextsi128_si512(__m128i __a)
/usr/lib/clang/13.0.1/include/avx512fintrin.h:_mm512_zextsi256_si512(__m256i __a)
/usr/lib/clang/14.0.1/include/avxintrin.h:_mm256_zextsi128_si256(__m128i __a)
/usr/lib/clang/14.0.1/include/avx512fintrin.h:_mm512_zextsi128_si512(__m128i __a)
/usr/lib/clang/14.0.1/include/avx512fintrin.h:_mm512_zextsi256_si512(__m256i __a)
grep: /usr/lib/dri/r600_dri.so: No such file or directory
grep: /usr/lib/dri/r300_dri.so: No such file or directory
grep: /usr/lib/dri/i965_dri.so: No such file or directory
grep: /usr/lib/dri/i915_dri.so: No such file or directory
/usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/include/avx512fintrin.h:_mm512_zextsi128_si512 (__m128i __A)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/include/avx512fintrin.h:_mm512_zextsi256_si512 (__m256i __A)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/include/avxintrin.h:_mm256_zextsi128_si256 (__m128i __A)
```

**Comment by KungFuJesus** [comment]
Come to think of it, the earliest clang I think I tried might have been clang 9.  It could be that you just need to modify the macro that checks clang versions and have one that checks back further.  I kept going as far back as I could but I don't remember how far back I had went.  I think we have a CI system building on clang 7, though.

**Comment by mtl1979** [comment]
AppleClang use own version numbering... It was forked from official Clang sources a long time ago...
What we need is testing with every possible AppleClang version until the symbols are defined... If there is none currently, then we can just use the fallback version until it is added...

**Comment by seanm** [comment]
I have a patch coming...

**Comment by phprus** [comment]
``_mm256_zextsi128_si256`` is present beginning with ``clang 5`` (compare https://github.com/llvm/llvm-project/blob/release/4.x/clang/lib/Headers/avxintrin.h and https://github.com/llvm/llvm-project/blob/llvmorg-5.0.0/clang/lib/Headers/avxintrin.h)

AppleClang 8 ~ Clang 3.9
...
AppleClang 9.1.0  (Xcode 9.3) ~ Clang 5

See: https://en.wikipedia.org/wiki/Xcode#Xcode_7.0_-_10.x_(since_Free_On-Device_Development)_2 (Table "Toolchain version history")

**Comment by seanm** [comment]
I already know it's not present in Xcode 8.2.1 but is 10.1.  Haven't squeezed all the way yet.

**Comment by mtl1979** [comment]
I know it takes quite a while to find the exact release that added it, but it helps a lot when we don't constantly have to edit the test that enables the fallback... It's very easy to break the test for other compilers when trying to figure out what defines each compiler has.

**Comment by seanm** [comment]
>I know it takes quite a while to find the exact release that added it

Not really. I already have every Xcode version on my NAS, I just need to grep.  But today is looking hectic...

**Comment by mtl1979** [comment]
> > I know it takes quite a while to find the exact release that added it
> 
> Not really. I already have every Xcode version on my NAS, I just need to grep. But today is looking hectic...

I have official Clang and GCC versions starting from 6.0 and ending with current release... I also have Visual C++ 2015, 2017, 2019 and 2022 on same machine. I used to have Linaro embedded gcc also on my old development PC.

**Comment by seanm** [comment]
So Xcode 9.2 has no `_mm256_zextsi128_si256`, but Xcode 9.3 does.  Now to find the `__apple_build_version__` value...

**Comment by phprus** [comment]
@seanm
```c
#if defined(__apple_build_version__) && ((__clang_major__ > 9) || (__clang_major__ == 9 && __clang_minor__ >= 1))
   // _mm256_zextsi128_si256 available
#endif
```

**Comment by KungFuJesus** [comment]
This is fixed, it can be closed.
